server:
  port: 8080

spring:
  application:
    name: user-module

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

